import fs from'node:fs/promises';import crypto from'node:crypto';
const S=[
{id:'contabeis',brand:'Contábeis',name:'Portal Contábeis',cat:'Tributos Federais',desc:'Discussões e atualizações sobre tributos federais.',logo:'https://www.google.com/s2/favicons?domain=contabeis.com.br&sz=128',portal:'https://www.contabeis.com.br/forum/3/tributos-federais/',rss:'https://www.contabeis.com.br/rss/forum/3/tributos-federais/'},
{id:'receita',brand:'Receita Federal',name:'Receita Federal',cat:'Notícias Oficiais',desc:'Comunicados e atualizações oficiais.',logo:'https://www.google.com/s2/favicons?domain=gov.br&sz=128',portal:'https://www.gov.br/receitafederal/pt-br/assuntos/noticias',rx:/href="([^"]*\/receitafederal\/pt-br\/assuntos\/noticias\/\d{4}\/[^"]+)"[^>]*>([\s\S]*?)<\/a>/gi},
{id:'iob-r',brand:'IOB',name:'IOB - Reforma Tributária',cat:'Reforma Tributária',desc:'Cobertura sobre IBS, CBS e transição tributária.',logo:'https://www.google.com/s2/favicons?domain=noticias.iob.com.br&sz=128',portal:'https://noticias.iob.com.br/editoria/reforma-tributaria/direto-de-brasilia/',rx:/href="(https:\/\/noticias\.iob\.com\.br\/(?!editoria)[^"]+)"[^>]*>([\s\S]*?)<\/a>/gi},
{id:'iob-f',brand:'IOB',name:'IOB - Tributária/Fiscal',cat:'Tributário e Fiscal',desc:'Obrigações, legislação e rotina fiscal.',logo:'https://www.google.com/s2/favicons?domain=noticias.iob.com.br&sz=128',portal:'https://noticias.iob.com.br/editoria/tributaria-fiscal/',rx:/href="(https:\/\/noticias\.iob\.com\.br\/(?!editoria)[^"]+)"[^>]*>([\s\S]*?)<\/a>/gi},
{id:'cgibs',brand:'CGIBS',name:'CGIBS',cat:'IBS',desc:'Notícias oficiais do Comitê Gestor do IBS.',logo:'https://www.google.com/s2/favicons?domain=cgibs.gov.br&sz=128',portal:'https://www.cgibs.gov.br/noticias',rx:/href="(https?:\/\/(?:www\.)?cgibs\.gov\.br\/(?!noticias|inicial)[^"]+)"[^>]*>([\s\S]*?)<\/a>/gi},
{id:'jota',brand:'JOTA',name:'JOTA - Tributos',cat:'Tributos',desc:'Análises sobre tributação, CARF e tribunais.',logo:'https://www.google.com/s2/favicons?domain=jota.info&sz=128',portal:'https://www.jota.info/tributos',rx:/href="(https:\/\/(?:www\.)?jota\.info\/tributos\/[^"]+)"[^>]*>([\s\S]*?)<\/a>/gi}];
const C=s=>(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const tag=(b,n)=>C((b.match(new RegExp(`<${n}[^>]*>([\\s\\S]*?)<\\/${n}>`,'i'))||[])[1]);const abs=(u,b)=>{try{return new URL(u,b).href}catch{return u}};const themes=s=>{let b=s.toLowerCase(),m={'Reforma Tributária':['reforma'],'IBS/CBS':['ibs','cbs'],'ICMS':['icms','confaz'],'Simples Nacional':['simples','mei'],'Tributos Federais':['irpj','irrf','pis','cofins','dctf','reinf','carf'],'NF-e/SPED':['nf-e','nfs-e','sped','df-e'],'Trabalhista':['trabalhista','fgts','esocial']},r=Object.entries(m).filter(([,w])=>w.some(x=>b.includes(x))).map(([k])=>k);return r.length?r:['Tributos Federais']};
let news=[],sources=[];for(const s of S){let count=0,error='';try{let r=await fetch(s.rss||s.portal,{headers:{'user-agent':'Mozilla/5.0 RadarFiscal/7.0'},signal:AbortSignal.timeout(35000)});if(!r.ok)throw Error('HTTP '+r.status);let raw=await r.text(),seen=new Set;if(s.rss){for(const b of raw.match(/<item\b[\s\S]*?<\/item>/gi)||[]){let title=tag(b,'title'),url=tag(b,'link'),summary=tag(b,'description').slice(0,300);if(!title||!url||seen.has(url))continue;seen.add(url);news.push(make(s,title,summary,url,tag(b,'pubDate')));if(++count>=18)break}}else for(const m of raw.matchAll(s.rx)){let url=abs(m[1],s.portal),title=C(m[2]);if(title.length<12||seen.has(url))continue;seen.add(url);let near=C(raw.slice(Math.max(0,m.index-180),m.index+m[0].length+420)),date=(near.match(/\d{1,2}\/\d{1,2}\/\d{4}(?:\s*[|\-]\s*\d{1,2}(?::|h)\d{2})?/)||[])[0]||'',summary=near.replace(title,'').slice(0,300);news.push(make(s,title,summary,url,date));if(++count>=15)break}}catch(e){error=e.message}sources.push({id:s.id,brand:s.brand,name:s.name,category:s.cat,description:s.desc,logo:s.logo,portal:s.portal,count,lastUpdated:new Date().toISOString(),error})}function make(s,title,summary,url,publishedAt){return{id:crypto.createHash('sha256').update(s.id+url).digest('hex').slice(0,16),capturedAt:new Date().toISOString(),sourceId:s.id,sourceBrand:s.brand,sourceName:s.name,category:s.cat,title,summary,url,publishedAt,themes:themes(title+' '+summary)}}news=[...new Map(news.map(x=>[x.url,x])).values()];let old={news:[]};try{old=JSON.parse(await fs.readFile('docs/data/noticias.json','utf8'))}catch{};if(!news.length)news=old.news||[];await fs.writeFile('docs/data/noticias.json',JSON.stringify({updatedAt:new Date().toISOString(),sources,news},null,2));console.log(news.length+' conteudos');
