import fs from 'node:fs/promises';import crypto from 'node:crypto';
const sources=[
{id:'contabeis',brand:'Contábeis',name:'Portal Contábeis',category:'Tributos Federais',description:'Discussões e atualizações sobre tributos federais.',icon:'CT',logo:'https://www.google.com/s2/favicons?domain=contabeis.com.br&sz=128',portal:'https://www.contabeis.com.br/forum/3/tributos-federais/',rss:'https://www.contabeis.com.br/rss/forum/3/tributos-federais/'},
{id:'receita',brand:'Receita Federal',name:'Receita Federal',category:'Notícias Oficiais',description:'Comunicados e atualizações oficiais da Receita Federal.',icon:'RF',logo:'https://www.google.com/s2/favicons?domain=gov.br&sz=128',portal:'https://www.gov.br/receitafederal/pt-br/assuntos/noticias',linkRx:/href="([^"]*\/receitafederal\/pt-br\/assuntos\/noticias\/\d{4}\/[^"]+)"[^>]*>([\s\S]*?)<\/a>/gi},
{id:'iob-r',brand:'IOB',name:'IOB - Reforma Tributária',category:'Reforma Tributária',description:'Cobertura sobre IBS, CBS e transição tributária.',icon:'IOB',logo:'https://www.google.com/s2/favicons?domain=noticias.iob.com.br&sz=128',portal:'https://noticias.iob.com.br/editoria/reforma-tributaria/direto-de-brasilia/',linkRx:/href="(https:\/\/noticias\.iob\.com\.br\/(?!editoria)[^"]+)"[^>]*>([\s\S]*?)<\/a>/gi},
{id:'iob-f',brand:'IOB',name:'IOB - Tributária/Fiscal',category:'Tributário e Fiscal',description:'Obrigações, legislação e rotina fiscal.',icon:'IOB',logo:'https://www.google.com/s2/favicons?domain=noticias.iob.com.br&sz=128',portal:'https://noticias.iob.com.br/editoria/tributaria-fiscal/',linkRx:/href="(https:\/\/noticias\.iob\.com\.br\/(?!editoria)[^"]+)"[^>]*>([\s\S]*?)<\/a>/gi},
{id:'cgibs',brand:'CGIBS',name:'CGIBS',category:'IBS',description:'Notícias oficiais do Comitê Gestor do IBS.',icon:'IBS',logo:'https://www.google.com/s2/favicons?domain=cgibs.gov.br&sz=128',portal:'https://www.cgibs.gov.br/noticias',linkRx:/href="(https?:\/\/(?:www\.)?cgibs\.gov\.br\/(?!noticias|inicial)[^"]+)"[^>]*>([\s\S]*?)<\/a>/gi},
{id:'jota',brand:'JOTA',name:'JOTA - Tributos',category:'Tributos',description:'Análises e notícias sobre tributação, CARF e tribunais.',icon:'JOTA',logo:'https://www.google.com/s2/favicons?domain=jota.info&sz=128',portal:'https://www.jota.info/tributos',linkRx:/href="(https:\/\/(?:www\.)?jota\.info\/tributos\/[^"]+)"[^>]*>([\s\S]*?)<\/a>/gi}
];
const clean=s=>(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/\s+/g,' ').trim();
const tag=(x,n)=>clean((x.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,'i'))||[])[1]);const abs=(u,b)=>{try{return new URL(u,b).href}catch{return u}};
const classify=s=>{const b=s.toLowerCase(),m={'Reforma Tributária':['reforma tributária','reforma','plp'],'IBS/CBS':['ibs','cbs'],'ICMS':['icms','confaz'],'Simples Nacional':['simples nacional','mei'],'Tributos Federais':['irpj','irrf','pis','cofins','dctf','reinf','carf'],'NF-e/SPED':['nf-e','nfs-e','sped','df-e','dfe'],'Trabalhista':['trabalhista','fgts','esocial','e-social']};const r=Object.entries(m).filter(([,w])=>w.some(x=>b.includes(x))).map(([k])=>k);return r.length?r:['Tributos Federais']};
const fetchText=async u=>{const r=await fetch(u,{headers:{'user-agent':'Mozilla/5.0 (compatible; RadarFiscal/4.0)'},redirect:'follow',signal:AbortSignal.timeout(35000)});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.text()};
let news=[],status=[];
for(const s of sources){let count=0,error='';try{const raw=await fetchText(s.rss||s.portal),seen=new Set();if(s.rss){for(const block of raw.match(/<item\b[\s\S]*?<\/item>/gi)||[]){const title=tag(block,'title'),url=tag(block,'link'),summary=tag(block,'description').slice(0,300),publishedAt=tag(block,'pubDate');if(!title||!url||seen.has(url))continue;seen.add(url);news.push({id:crypto.createHash('sha256').update(s.id+url).digest('hex').slice(0,16),capturedAt:new Date().toISOString(),sourceId:s.id,sourceBrand:s.brand,sourceName:s.name,category:s.category,title,summary,url,publishedAt,themes:classify(title+' '+summary)});if(++count>=18)break}}else{for(const m of raw.matchAll(s.linkRx)){const url=abs(m[1],s.portal),title=clean(m[2]);if(title.length<12||seen.has(url))continue;seen.add(url);const near=clean(raw.slice(Math.max(0,m.index-200),Math.min(raw.length,m.index+m[0].length+450)));const date=(near.match(/\b\d{1,2}\/\d{1,2}\/\d{4}(?:\s*[|\-–]\s*\d{1,2}(?::|h)\d{2}(?:min)?)?/i)||[])[0]||'';let summary=near.replace(title,'').replace(/^(Início|Notícias|Tributos Federais)\s*/i,'').slice(0,300);news.push({id:crypto.createHash('sha256').update(s.id+url).digest('hex').slice(0,16),capturedAt:new Date().toISOString(),sourceId:s.id,sourceBrand:s.brand,sourceName:s.name,category:s.category,title,summary,url,publishedAt:date,themes:classify(title+' '+summary)});if(++count>=15)break}}}catch(e){error=String(e.message||e).slice(0,180)}status.push({...s,count,lastUpdated:new Date().toISOString(),error,linkRx:undefined})}
news=[...new Map(news.map(x=>[x.url,x])).values()];let old={news:[]};try{old=JSON.parse(await fs.readFile('docs/data/noticias.json','utf8'))}catch{};const usedCache=!news.length;if(usedCache)news=old.news||[];await fs.writeFile('docs/data/noticias.json',JSON.stringify({updatedAt:new Date().toISOString(),total:news.length,sources:status,news,usedCache},null,2));console.log(`Gerado: ${news.length}; falhas: ${status.filter(x=>x.error).length}`);
